#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: $0 <url>" 
  exit
fi

if [ -z $SHORTY_API_KEY ]; then
  echo "Environment variable named 'SHORTY_API_KEY' must be set"
  exit
fi

api_key=$SHORTY_API_KEY
api_url="https://www.googleapis.com/urlshortener/v1/url?key=$api_key"
curl -s -XPOST "$api_url" -H "Content-Type: application/json" -d "{\"longUrl\": \"$1\"}" | grep "\"id\":" | sed 's/.*"id": "\(.*\)",/\1/g'
